# Generated by Django 5.2.4 on 2025-07-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_rename_subject_teacher_subject_speciality_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="grade",
        ),
    ]
