# Generated by Django 5.2.4 on 2025-07-20 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_remove_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(related_name="courses", to="myApp.student"),
        ),
        migrations.AlterField(
            model_name="course",
            name="code",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="myApp.teacher",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="myApp.course",
            ),
        ),
        migrations.AlterField(
            model_name="result",
            name="marks_obtained",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="result",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="myApp.student",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="roll_number",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
